### ISSUE TITLE
Official elastic journalbeat

### ISSUE THREAD

**Issue by pontostroy** [mheese/journalbeat#157]
https://github.com/elastic/beats/tree/master/journalbeat

Is this the  end of mheese/journalbeat?

**Comment by mheese** [comment]
looks like it!

**Comment by mheese** [comment]
I haven't been able to work on this since months, and tried several advances towards Elastic to take it over without any success. Looks like they have finally noticed that this is a needed concept.

**Comment by nrvnrvn** [comment]
This is the best what could happen to mheese/journalbeat

But yet it is strange they seem to have done everything from scratch as if this repo did not exist.

**Comment by mheese** [comment]
yeah, I agree.

**Comment by tsg** [comment]
@mheese Hey, this is Tudor from Elastic. I came here to give you a heads-up that we're going to release "our" Journalbeat soon and found this ticket :). I apologize for not contacting you about it earlier. To give you some background, we wanted for long Journald support, but we wanted it in Filebeat and that was not easy for a couple of reasons. One has to do with the internal Filebeat architecture and the other has to do with us not wanting to link at compile time against the journald libs. 

Realizing that the Filebeat refactoring is still a few months away, we didn't want to keep postponing our journald support, so a few weeks back we decided to bite the bullet and release elastic/journalbeat as experimental. We still intend for it to become a Filebeat input in the near future, which is why the Elastic Journalbeat has an internal architecture that resembles Filebeat's. That's mostly why we've started from scratch.

We really appreciate you maintaining Journalbeat for all this time, I think it helped a lot of people. And sorry for not handling this better on our side. Let me know if you have any questions. I'll ask our community people to send you a swag package as a thank you note :)

**Comment by nrvnrvn** [comment]
@tsg 
Hi! Please take a chance and review this beat’s filtering capabilities
https://github.com/mheese/journalbeat/blob/master/etc/journalbeat.yml#L56
Filtering specific identifiers, units and kernel messages is something end users requested and made contributions to this repo.

They will definitely be willing to migrate to elastic/journalbeat and they will definitely want to preserve backwards compatibility in terms of features.

Feel free to ask any questions.

**Comment by mheese** [comment]
@tsg Hey Tudor, it's good to hear from you! Yeah, I remember you told me about those plans a long time ago - at KubeCon in Berlin last year when we met.

It's pretty awesome to see that you guys are finally integrating journald support. As @nrvnrvn pointed out, there are some filters/rewrites in this package that people might expect to be in your version as well.

Are you guys okay if I start putting up a deprecation notice and point to the official repo now?

**Comment by tsg** [comment]
Thanks @mheese and @nrvnrvn, we're going to check the filters. Pinging @urso and @kvch.

> Are you guys okay if I start putting up a deprecation notice and point to the official repo now?

Yes, that sounds good to me.

**Comment by kvch** [comment]
@nrvnrvn In this case the filters are definitely to be supported. My initial intention was to see what users would like to see in terms of filtering before adding too many configuration options. :)

**Comment by jimmywan** [comment]
>Are you guys okay if I start putting up a deprecation notice and point to the official repo now?

Perhaps time to archive the repo?

**Comment by nrvnrvn** [comment]
I've put the deprecation notice.
