### ISSUE TITLE
Publishing one event at a time not optimal

### ISSUE THREAD

**Issue by kinghrothgar** [mheese/journalbeat#36]
So I just wanted to create this as a placeholder just in case someone wanted to work on it before I got around to it. Currently, each event is published one at a time. This ensures that each event is published successfully and makes it easy to keep track of where in the journal to resume after exit.  In most cases, this is adequate. I have encountered that when a problem occurs in some of our high traffic applications that cause several hundred logs to be written in a second it can cause journalbeat to fall behind. In extreme cases, it has taken journalbeat hours to catch up. I believe this could be remedied by using one of the batch publishing options in libbeat.

**Comment by nicorevin** [comment]
I got this remedied by removing `publisher.Sync`:
```diff
--- a/beat/journalbeat.go
+++ b/beat/journalbeat.go
@@ -292,7 +292,7 @@ func Publish(beat *beat.Beat, jb *Journalbeat) {
 
                // publish the event now
                //m := (common.MapStr)(ev)
-               success := jb.output.PublishEvent(m, publisher.Sync, publisher.Guaranteed)
+               success := jb.output.PublishEvent(m, publisher.Guaranteed)
                // should never happen but if it does should definitely log an not save cursor
                if !success {
                        logp.Err("PublishEvent returned false for cursor %s", ev["__CURSOR"])
```
But it is still in test though.
Refs:
https://godoc.org/github.com/elastic/beats/libbeat/publisher
https://discuss.elastic.co/t/safely-publish-an-event-using-libbeat/52395/3

**Comment by kinghrothgar** [comment]
The second ref link is a thread I started 😃  

So that's probably a much simpler route than doing multiple publish. I had forgotten that you could make publish event async. However,  If journalbeat is told to exit, I don't believe it will wait until events that are queued up are sent.  If journalbeat crashes, the events that are queued up will definitely be lost. I think the cursor routine should be expanded to track the signal sent by the  publisher.Signal callback option to remedy this.

Another caveat with this route is under extreme loads like I described journalbeat could read in from journald faster than journalbeat can send. It appears there's a QueueSize option for ShipperConfig that I assume sets this queue size. I wonder what will happen when it is filled.

**Comment by mheese** [comment]
This is definitely something we need to address. I just ran into this problem myself 😃 

One thing to keep in mind though is that depending on your `journald.conf` settings the cursor only works for certain `Storage` options. Ideally I would like this to work even with `Storage=none` and queue/buffer the events in _journalbeat_ in the meantime.

Food for thought. Opinions @kinghrothgar @nicorevin ?

**Comment by mattupstate** [comment]
What about the back-pressure sensitive protocol  that logstash supports? Is that not designed to deal with this?

**Comment by kinghrothgar** [comment]
@mattupstate I will have to look into what Filebeat uses as it uses the protocol you are referring to. As far as I can tell that wont be a direct solution for the problem though. That would prevent journalbeat from overloading logstash or elasticsearch. In this case journalbeat is just going too slow as it's sending every single log synchronously one at a time.

**Comment by mattupstate** [comment]
Ahh, I see. I misunderstood the problem at hand.

**Comment by nicorevin** [comment]
has come across that while testing #38 
Whereas we still need to think about crash cases it seems weird that this  
>If journalbeat is told to exit, I don't believe it will wait until events that are queued up are sent`

indeed happens.
https://github.com/elastic/beats/blob/67d322e5c4e88a46a5609a0fadeb9581ba0b2c9b/libbeat/publisher/sync.go#L33-L37 I don't understand the rationale behind this...
See also https://github.com/elastic/beats/pull/2046

`publisher.Signal` could help with sending only the cursors of the successfully sent events.
But another problem arises here. If we use async (basically remove `publisher.Sync`) it will send signals back not in the order they arrive. So we can rely on the [RealtimeTimestamp](https://godoc.org/github.com/coreos/go-systemd/sdjournal#JournalEntry) field when deciding whether to overwrite the cursor or not.
But it won't help us recover from crash since the state we need to save is much broader then the latest successful cursor and it turns out that even casual shutdown leads to events' loss...

I wonder if any kind of WAL being dumped periodically to disk along with the cursor could help us recover from shutdown/crash.
