### ISSUE TITLE
Is there a chance of loosing an event if the PublishEvent fails?

### ISSUE THREAD

**Issue by xynova** [mheese/journalbeat#6]
I was just going through the code and noticed the cursor is being updated before confirmation of the event being published as an Event. 

https://github.com/mheese/journalbeat/blob/master/beat/journalbeat.go#L265

Does this mean, there is a chance of missing the event if something bad occurs in the jb.output.PublishEvent(m)?

**Comment by mheese** [comment]
'The cursor being updated' at this line is for persisting the current cursor position in regular intervals to the disk which is used in combination with the one config option (which tries to read the journal from the last "known" position).

That said, there is currently no error handling for events that have failed being published. My colleague is actually working on implementing this feature right now. However, originally I thought that this is something that libbeat would take care of (and I generally still think that this should be something that the framework takes care of), this is why it hasn't been in there from the start.

I will leave this ticket open to track that this is still a current issue.

**Comment by kinghrothgar** [comment]
Any chance there is a timeline for handling publish fails?  I actually started  using instead of my previous solution because I though it would handle publish / connection failures to logstash to prevent log loss.

If it's gonna be a while I have time to work on a solution also if you would like.

**Comment by mybarretto** [comment]
@mheese and I are planning on implementing something like Filebeat's registrar, but there is not currently a timeline set for this. Some items we think would be very important for this implementation would be:
- the buffer needs to have a configurable rotating size and time;
- it should ideally allow encryption on disk.
If you do have time to work on a solution, we would appreciate your collaboration. Otherwise, we will post an update when it starts taking shape.

**Comment by kinghrothgar** [comment]
@mheese @mybarretto, I should start implementing this in the next few days.  I was thinking though that a simpler and possibly better solution would be to stop the following the journal when a PublishEvent error happens and keep trying to send that event.  Once it goes through, resume following at that point.  Otherwise, we would be doubling everything stored in journald in our buffer until the endpoint came back up.

**Comment by xynova** [comment]
It sounds sensible as I can imagine keeping a duplicate stream of tons of
logs coming in would fill up the disk in half the time.

Having said this...one thing that can happen is that we get a journal log
rotate while the endpoint is gone and then badda blim, badda boom... logs
no more.

I am wondering if it would be possible to mix both ideas and re reroute
logs into a separate journald file that does not log rotate while the
endpoint is down (just an idea out of the blue)
