### ISSUE TITLE
systemd-journal-remote

### ISSUE THREAD

**Issue by ahmebane** [mheese/journalbeat#77]
First, thanks for this beat - very nice. 

Has anyone set up journalbeat to read journal entries arriving via system-journal-remote? I've tried a number of ideas with no success.

**Comment by mheese** [comment]
@ahmebane, no, this beat cannot be used to do that - and is also not intended to that. However, this would be an excellent idea for its own beat!

The reason why this beat is not meant to do that is because this beat is supposed to deliver logs in the "push" model, while journald-remote would be a "pull" model. There is a significant difference in the required infrastructure security model - the "push" model is what everybody is pretty much prepared for while the "pull" model requires a lot of network access.

From an application point of view I personally would actually prefer that pull model, however, this will never fly within our network admin group.

That said, this beat is about to become obsolete once the official `filebeat` supports journald. Then an alternative beat to support system-journal-remote would be a good thing to have - or maybe as a logstash plugin.

@ahmebane does this answer your question?

**Comment by ahmebane** [comment]
Well, I did get it to work with a very simple mod. I just changed journalbeat.go to open the journal like:
if jb.journal, err = sdjournal.NewJournalFromDir("/var/log/journal/remote")

Seems to be working. journal-remote can receive data either as a push or by doing pulls. (The so-called 'active' vs 'passive' mode). 

I'm still testing/experimenting. I really only need to receive a remote journal from a single host, so I may change the above line to NewJournalFromFile().

Thanks @mheese.

**Comment by mheese** [comment]
@ahmebane oh I see! I didn't know there is a passive mode. I'm pretty sure the original discussions for journal-remote never mentioned that - I would remember that (although I also might be utterly wrong here).

Well, this changes things quite a bit to be honest. It doesn't sound like something very complicated to support to be honest. Although when you look at the code base here, it would probably add a lot of code as this is really a very simple program so far (and was never intended to go far beyond that).

@nicorevin what do you think: adding an array config variable that takes paths and opens these journals instead of the default one?

@ahmebane can you tell me about this "special situation" where you think that journalbeat would be the burden to the remote host?

With regards to filebeat supporting journal, this is something that @tsg and I discussed at KubeCon in March this year, and he mentioned that this is on the list. However, quickly looking at the repo, I don't really see it mentioned anywhere.

**Comment by nicorevin** [comment]
@mheese sounds pretty feasible, will add options for both ` NewJournalFromFiles` and ` NewJournalFromDir` (mutually exclusive).

As for filebeat it is curious to hear. Filebeat is dealing with plain text files and we are binding to the unix socket to read from binary files.

Anyway if such a decision is ever to be made I would be happy to participate (though I am not sure it makes that much sense).

**Comment by mheese** [comment]
@nicorevin if we make it a feature, we should make it an array, and determine if it is a file or a folder and use the appropriate call
