### ISSUE TITLE
Replace user id with user name

### ISSUE THREAD

**Issue by fholzer** [mheese/journalbeat#87]
First off, kudos for this project.

For my personal use I prefer to see user names instead of user ids, so I forked this project and made the necessary changes. (https://github.com/fholzer/journalbeat/tree/user-id-to-name)
I'm not quite happy with it as it is right now, as I'm having concerns over how expensive the user id lookup is. Would rather cache the user id-to-name mapping in memory. Maybe I get some time to look into that during the weekend.

I'm new to Beats, and new to golang, so if there's some easier way to accomplish this, please let me know.

If this is something more people are interested in, let me know, otherwise feel free to close this issue.

cheers

**Comment by mbrooks** [comment]
I guess I am failing to understand what issue this is resolving. Is there a technical issue that this is resolving or is it a personal preference?

**Comment by mheese** [comment]
I can understand this. Especially when you are globally ingesting logs from a lot of different servers, UIDs (especially if they are coming from local directories like `/etc/passwd`) don't mean a lot, and can refer to the same or different user names.

Not sure the reasons why `journald` does not resolve uids, but let's not forget that this is also a trusted field in journald ( `_UID`). Take a look at https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html for reference.

It's not a difficult task to cache the UIDs -> usernames. However, there is another problem. The problem that I see here is, that especially if you're looking at logs from containers (or any namespaced service), the uid -> username function is not easily determined or is just plainly wrong (depending on your point of view or goal). There are also cases where you might not be able to resolve at all, and a uid in a container can refer to a completely different username than in the OS. From the OS point of view the OS resolution is what counts and what will determine rights. However, that might not be the username you are interested in.

That is actually a general problem in containers. Docker is addressing that with user namespaces (_userns_). See https://docs.docker.com/engine/security/userns-remap/ for details. However, I'm not so sure if every container runtime has dealt with it yet, and what our approach here should be.

Anyway, thanks @fholzer for pointing this out. This is something that we should add imho. And also thanks for taking a first shot at this. Not easy I bet especially if you are not familiar with golang yet.

**Comment by mheese** [comment]
@nicorevin, your opinion here matters :)

**Comment by nicorevin** [comment]
I've never thought about that.
If I had to worry about the user identity I would rather worry about the whole bunch of parameters including both uid and gid and and their appropriate names and other *ids that would form a unique fingerprint of a user, machine, event and context.
And I would rather not try to guess this info using os/user but to retrieve from the journal entry itself.

Here is an example:
- we create a user with a random id,
- exec some process from the user's name and then
- perform a cleanup and delete the user.

Even a small gap between the time the user has been deleted and an attempt to make a getuid() call will lead to fail. 

That's why I would want systemd to log this info at the time the event occurs if I were interested in a more detailed information about the user. And eventually I would land [somewhere here](https://github.com/systemd/systemd/blob/52b1478414067eb9381b413408f920da7f162c6f/src/journal/journald-server.c#L767) and either ask to extend it or extend it myself.

It is a long path but a proper one.

**Comment by fholzer** [comment]
Still, don't you think it would make sense to offer this feature? Maybe disable by default, with a switch in the config file, and maybe also a few sentences on why it doesn't make sense to use it in certain setups.

**Comment by mheese** [comment]
@nicorevin, you are making some valid points there. Another complication that popped into my head is that setuid/setgid programs should be dealt with as well.

The problem here is that systemd/journald is all about accuracy at all times (which it should because this is also a security and audit concern). However, during normal operation these problems of changing user/group names are corner cases. In log parsing / analysis one is normally satisfied with an abbreviation (except for audit logs where accuracy matters as well). It's better to have more data than less.

I agree with @nicorevin that what he has described is the "proper" way. I doubt that a patch there would get accepted though because this probably has too much performance impact or would be rejected because of security concerns and inaccuracy.

However, I also agree with @fholzer that this is a feature that people would like to have (me for example). We need to find a middle ground imho.

That said, we cannot have these type of feature requests dropping in like that. I can imagine a lot of custom feature requests like this, and it would complicate the code. Maybe we should think of a "plugin"-style architecture (geez, I hate it already - plugins are always trouble 😄) where one could load custom log transformers. Since golang 1.8 in Linux there is finally the possibility to do that (https://golang.org/pkg/plugin/). In journalbeat we don't need to be platform independent, so that it is Linux only is not a problem. It's using ltdl afaik - I haven't looked at it in too much detail yet. I'd like to stay away from `cmd.Exec` style extensions as the penalty would be too much. However, with a well defined interface and plugins - we would be able to let people load any kind of transformer that they would like to use.

@nicorevin what do you think?

**Comment by fholzer** [comment]
Just noticed that elastic is doing something similar (lookup and cache user/group names)
https://www.elastic.co/guide/en/beats/libbeat/6.3/_added.html
see https://github.com/elastic/beats/pull/6978

At work right now, will check in detail later today.

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
